import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ReactHtmlParser from 'react-html-parser';

const recurrencies = [
  {
    description: "Anual com 47% OFF",
    frequency: "anual",
    id: 18,
    months: 12,
    paymentType: "creditCard",
    price: 189
  },
  {
    description: "Mensal sem desconto",
    frequency: "mensal",
    id: 19,
    months: 1,
    paymentType: "creditCard",
    price: 357
  },
  {
    description: "Anual com 47% OFF",
    frequency: "anual",
    id: 23,
    months: 12,
    paymentType: "bankSlip",
    price: 189
  },
]

export default function Home() {
  const recurrencyId = 18;
  
  function findMyRecurrency() {
    let recurrency = 0;
    
    recurrencies.forEach(r => {if (r.id === recurrencyId) return recurrency = r.price * r.months});


    return recurrency;
  }

  console.log(findMyRecurrency(recurrencies));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {findMyRecurrency(recurrencies)}
        </h1>
      </main>
    </div>
  )
}
